_format_version: "3.0"
consumers:
  - custom_id: owntracks
    keyauth_credentials:
      - key: djfu47dHSfmOid83K03kd02isSKJXbY9
    tags:
      - geo
      - geolocation
      - tracker
    username: owntracks
  - custom_id: timetracker-ui
    keyauth_credentials:
      - key: Loak38Jue7Gtw5stGabYx6xb4sgXgsFS
    tags:
      - ui
      - frontend
      - timetracker
    username: timetracker-ui
  - custom_id: uptime-kuma
    username: uptime-kuma
    keyauth_credentials:
      - key: GiHXjgRKs3gEDJjyfovJsP8pzUkjEJTi
    tags:
      - ui
      - frontend
      - kuma
      - health
  - custom_id: service-monitor
    keyauth_credentials:
      - key: abc123
    tags:
      - health
      - servicemon
    username: service-monitor
plugins:
  - name: correlation-id
    enabled: true
    config:
      echo_downstream: true
      generator: "uuid#counter"
      header_name: X-correlation-id
    protocols:
      - grpc
      - grpcs
      - http
      - https
  - name: prometheus
    enabled: false
    config:
      bandwidth_metrics: true
      latency_metrics: true
      per_consumer: false
      status_code_metrics: true
      upstream_health_metrics: false
    protocols:
      - grpc
      - grpcs
      - http
      - https
  - name: http-log
    enabled: false
    config:
      content_type: application/json
      custom_fields_by_lua: null
      flush_timeout: 2
      headers: null
      http_endpoint: "http://loki-router:30500/api/log"
      keepalive: 60000
      method: POST
      queue_size: 1
      retry_count: 10
      timeout: 10000
    protocols:
      - grpc
      - grpcs
      - http
      - https
  - name: key-auth
    enabled: true
    protocols:
      - http
      - https
    config:
      anonymous: null
      hide_credentials: false
      key_in_body: false
      key_in_header: true
      key_in_query: false
      key_names:
        - api-key
      run_on_preflight: true
  - name: file-log
    enabled: false
    protocols:
      - http
      - https
    config:
      reopen: false
      path: /usr/local/kong/logs/system.log
services:
  - name: timetracker-entries
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/entries
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-entries
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/entries
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-geofences
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/geofences
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-geofences
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/geofences
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-geotrack
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/geotrack
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-geotrack
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/geotrack
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-admin
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/admin
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-admin
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/admin
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-toggles
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/toggles
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-toggles
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/toggles
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-stats
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/stats
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-stats
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/stats
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-statistics
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/statistics
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-statistics
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/statistics
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-properties
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/properties
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-properties
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/properties
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-users
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/users
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-users
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/users
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-auth
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/auth
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-auth
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/auth
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-log
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/log
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-log
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/log
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-ping
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/ping
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-ping
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/ping
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-version
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/version
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-version
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/version
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-experiment
    connect_timeout: 5000
    enabled: false
    host: timetracker
    path: /api/experiment
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-experiment
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/experiment
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
  - name: timetracker-health
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/health
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-health
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/health
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
    plugins:
      - name: proxy-cache
        enabled: true
        protocols:
          - http
          - https
        config:
          cache_control: false
          cache_ttl: 120
          content_type:
            - text/plain
            - application/json
            - application/json; charset=utf-8
          ignore_uri_case: false
          memory:
            dictionary_name: kong_db_cache
          request_method:
            - GET
            - HEAD
          response_code:
            - 200
            - 301
            - 404
          response_headers:
            X-Cache-Key: true
            X-Cache-Status: true
            age: true
          strategy: memory
  - name: timetracker-schedule
    connect_timeout: 5000
    enabled: true
    host: timetracker
    path: /api/schedule
    port: 30000
    protocol: http
    read_timeout: 5000
    write_timeout: 5000
    retries: 0
    routes:
      - name: timetracker-schedule
        https_redirect_status_code: 426
        path_handling: v1
        paths:
          - /timetracker/api/schedule
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
