_format_version: "3.0"
services:
  - connect_timeout: 60000
    enabled: true
    host: mockbin.org
    name: mockbin
    port: 80
    protocol: http
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: root
        path_handling: v0
        paths:
          - /mockbin
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
    write_timeout: 60000
  - connect_timeout: 60000
    enabled: true
    host: nobio.myhome-server.de
    name: timetracker
    path: /api
    port: 443
    protocol: https
    read_timeout: 60000
    retries: 5
    routes:
      - https_redirect_status_code: 426
        name: timetracker
        path_handling: v1
        paths:
          - /api
        preserve_host: false
        protocols:
          - http
          - https
        regex_priority: 0
        request_buffering: true
        response_buffering: true
        strip_path: true
    write_timeout: 60000
